create schema discussit;
use discussit;

CREATE TABLE users(
    id INT NOT NULL AUTO_INCREMENT,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(60) NOT NULL,
	dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);


CREATE TABLE groups1(
	GId INT NOT NULL AUTO_INCREMENT,
	GName VARCHAR(50) NOT NULL,
	Gdesc VARCHAR(200) NOT NULL,
	id INT NOT NULL,
	dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (GId),
	UNIQUE(GName),
	FOREIGN KEY(id) REFERENCES users(id)
		ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE groupmembers(
	GId INT NOT NULL,
	id INT NOT NULL,
	auth INT NOT NULL DEFAULT 0,
	PRIMARY KEY(GId, id),
	FOREIGN KEY(GId) REFERENCES groups1(GId)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(id) REFERENCES users(id)
		ON DELETE CASCADE ON UPDATE CASCADE
	

);

CREATE TABLE questions(
	QId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id INT NOT NULL,
	GId INT NOT NULL,
	Topic VARCHAR(100) NOT NULL,
	Question VARCHAR(10000) NOT NULL,
	dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(id) REFERENCES users(id)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(GId) REFERENCES groups1(GId)
		ON DELETE CASCADE ON UPDATE CASCADE
	
);

CREATE TABLE answers(
	AnswerId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	QId INT NOT NULL,
	id INT NOT NULL,
	Answer VARCHAR(10000) NOT NULL,
	dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(QId) REFERENCES questions(QId)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(id) REFERENCES users(id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE invites(
	GId INT NOT NULL,
	userId INT NOT NULL,
	inviteId INT NOT NULL,
	GName VARCHAR(50) NOT NULL,
	InviterEmail VARCHAR(50) NOT NULL,
	PRIMARY KEY(GId, userId),
	FOREIGN KEY(userId) REFERENCES users(id)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(GId) REFERENCES groups1(GId)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(GName) REFERENCES groups1(GName)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(inviteId) REFERENCES users(id)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(InviterEmail) REFERENCES users(Email)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE faq(
	faqId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id INT NOT NULL,
	GId INT NOT NULL,
	Topic VARCHAR(100) NOT NULL,
	Question VARCHAR(10000) NOT NULL,
	dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(id) REFERENCES users(id)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(GId) REFERENCES groups1(GId)
		ON DELETE CASCADE ON UPDATE CASCADE
);