create schema discussit;
use discussit;


CREATE TABLE USERS(
	ID INTEGER(10) NOT NULL AUTO_INCREMENT,
	Email VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(60) NOT NULL
   	PRIMARY KEY (`ID`)
) AUTO_INCREMENT=1;

CREATE TABLE GROUPS1(
	GId INTEGER(10) NOT NULL PRIMARY KEY,
	GName VARCHAR(50) NOT NULL

);

CREATE TABLE GROUPMEMBERS(
	GId INTEGER(10) NOT NULL,
	id INTEGER(10) NOT NULL,
	PRIMARY KEY(GId, id),
	FOREIGN KEY(GId) REFERENCES GROUPS1(GId)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(id) REFERENCES USERS(id)
		ON DELETE CASCADE ON UPDATE CASCADE
	

);

CREATE TABLE QUESTIONS(
	QId INTEGER(15) NOT NULL PRIMARY KEY,
	id INTEGER(10) NOT NULL,
	Question VARCHAR(1000) NOT NULL,
	FOREIGN KEY(id) REFERENCES USERS(id)
		ON DELETE CASCADE ON UPDATE CASCADE
	
);

CREATE TABLE ANSWERS(
	AnswerId INTEGER(15) NOT NULL PRIMARY KEY,
	QId INTEGER(15) NOT NULL,
	id INTEGER(10) NOT NULL,
	Answer VARCHAR(10000) NOT NULL,
	FOREIGN KEY(QId) REFERENCES QUESTIONS(QId)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(id) REFERENCES USERS(id)
		ON DELETE CASCADE ON UPDATE CASCADE
);


